### ISSUE TITLE
Bochs configuration interface more like 86box 

### ISSUE THREAD

**Issue by stlintel** [bochs-emu/Bochs#368]
![image](https://github.com/user-attachments/assets/24735555-5df7-43c6-9be9-e939c5ebde64)

It is already half way there, just instead of opening separate window for configuration of CPU or Memory or Disk - do it on separate window on the left.

**Comment by stlintel** [comment]
For comparison how it looks today:

![image](https://github.com/user-attachments/assets/cc144860-83c7-460f-b49e-b12cb4d4326e)

**Comment by vruppert** [comment]
The win32 start/runtime menu rewrite is now ready for testing. I haven't added icons to the list box yet. I think this could be done later.

**Comment by stlintel** [comment]
Looks much better that before. But the size of the window is so jumpy ?
Sometimes resize doesn't even make sense:

<img width="771" height="548" alt="Image" src="https://github.com/user-attachments/assets/13bb4b34-372e-4460-8ddf-9f0762b1f6ad" />

I understood this is because one of the tabs asks window to be bigger.
Isn't it better to choose biggest window size required for all and stay with 1 size ?

Also some logical order between options would be good, I think Log File and Log Options can be merged into same dialog here and moved to end of the list. Same for plugin control.

**Comment by vruppert** [comment]
I have now appied some of your requested changes.

When I started the rewrite I thought it would be possible to create all dialog control for all list items in dialog init and the show only the ones for the selected item. The docs say that it should be possible to create up to 10000 user objects with no problem. In that case it would be easy to find out the biggest width and height for the dialog.
Then I found the issue with the big disk menu. As a normal dialog box there was no problem with the number of controls, but the new style main menu already has 32 static items defined. When I selected the big disk menu, some of the buttons on the left side of the dialog disappeared. When clicking on the tabs, one button appeared and another disappeared. I don't have code to hide these buttons, so I don't know why this happens. As a temporary solution I have the ATA stuff split into four menus.
The plugin control menu is important, especially if you decide to build a configuration from scratch. To make the code simpler and the handling identical weather or not plugins are enabled, the plugin.* file have a compatibility layer for the "non-plugin" mode. When starting Bochs, the plugin version looks at the plugin folder and builds a list of all plugin shared libraries / DLLs with their properties. With plugins disabled, this list is built at compile time. When initializing the parameters, all choices lists are built from the plugins list. With plugins disabled the load/unload commands simply call the related plugin entry point. In "init" mode this function creates the device object, creates parameters and installs a bochsrc option. The bochsrc parser treats unknown keywords as plugin to load if it is in the list.
That's why you cannot configure a network if no network device plugin is loaded. For the optional plugin control it might be better to use human readable names returned by the plugin entry function. The new fw_cfg device could be named "UEFI firmware control" then. Another point could be the addition of plugin loading by assigning a devive to a PCI slot. This is not present yet and it works for PCI add-on cards only. VGA compatible devices are selected with the VGA extension option and it includes plugin loading.

**Comment by fysnet** [comment]
It is looking nice. I have just a few comments.

If you have more than 5 or 6 USB ports, the window is to large and goes off the bottom of the screen without a scroll bar.

<img width="866" height="318" alt="Image" src="https://github.com/user-attachments/assets/9c4f8b7f-1f23-4c15-b339-884e478bbe5a" />

It would also be nice if the window title added the path and filename to the currently loaded bochsrc.txt file.
"Bochs Start Menu: C:\path\to\the\current\loaded\bochsrc.txt"

**Comment by vruppert** [comment]
The USB ports issue can be reproduced also at runtime when connecting a hub with "ports:8". The scroll window option already exists and it was formerly used by the huge "cpuid" list. If a bx_list_c has the USE_SCROLL_WINDOW property and the (flat) list has more than 16 items, the scoll window is activated. I need to write a function that also works if child lists exist.

The current bochsrc filename is currently only used internally in main.cc, but it shouldn't be hard to write a function that can be used by the config interface.

I have found another issue caused by selecting the VGA extension that needs some more work. The Voodoo and Geforce cards install a parameter when they are selected (loaded) in the active list. This confuses the existing dialog management and visible artifacts appear. My idea is to create a shared enum parameter that can be used for the VBE memsize, the Voodoo, Geforce and possibly Cirrus models. Since replacing a list item is not implemented, some work in the paramtree code is required.

**Comment by stlintel** [comment]
I suggest to split USB from serial/parallel and give him separate row in 'Options'

**Comment by vruppert** [comment]
Active bochsrc file name visible in title bar and separate USB configuration item are done. The scroll window stuff needs some more work since the original code was designed for a flat list only.

**Comment by vruppert** [comment]
The scroll window issue on Windows is fixed now, so the changes in the win32 start / runtime menu are complete from my point of view. Please let me know if something is missing or close this issue,

**Comment by stlintel** [comment]
I guess adding icons would some nice sugar but it is already looking much better than before.
I am fine closing the request

**Comment by Vort** [comment]
While I agree it's ok to close this exact issue, problem is not solved overall.
There are lots of other GUIs, many of which require similar treatment.

I understand that not every platform allows to have UI with such style.
But for ones which allow it, unification is the right thing to do.
