### ISSUE TITLE
Initialization failure of AGP videocard with 64 MB of VRAM

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#485]
When operating system tries to initialize AGP videocard with 64 MB of VRAM, such initialization instantly fails.

For example, this is what Windows 95 shows in such case:

![Image](https://github.com/user-attachments/assets/695f12d8-9efa-46ba-82d2-a3f97f392056)

![Image](https://github.com/user-attachments/assets/c82e21e7-6594-40b0-9d52-25022c05d8f2)

The following change in BIOS allows to get past this problem:
```diff
diff --git a/bochs/bios/rombios32.c b/bochs/bios/rombios32.c
index 8b136eb09..1e47ad5d8 100644
--- a/bochs/bios/rombios32.c
+++ b/bochs/bios/rombios32.c
@@ -815,7 +815,7 @@ static void pci_bios_init_bridges(PCIDevice *d)
         pci_config_writew(d, 0x20, 0xd000);
         pci_config_writew(d, 0x22, 0xd1f0);
         pci_config_writew(d, 0x24, 0xd200);
-        pci_config_writew(d, 0x26, 0xd3f0);
+        pci_config_writew(d, 0x26, 0xdaf0);
         pci_config_writeb(d, 0xee, 0x88);
       }
     } 
```

In my case, Windows 95 fails later because of different reason, but with Ubuntu 10.04.4 such solution works fine:

![Image](https://github.com/user-attachments/assets/f189b09a-ab54-4761-a191-4c91484cf6ac)

Despite this solution working fine, it may be better to figure out how to support arbitrary VRAM sizes, it may be useful for more modern videocards. However, I have no idea how to do this.

Version: 858c99de120f6dded10d86effa06ab21a52e0ed2

**Comment by aquaboxs** [comment]
Hey, where did you get the nVidia GeForce3 Ti 500 emulation on Bochs from it? Such as I can't find nVidia-related code across forks on Bochs.

Thanks.

**Comment by vruppert** [comment]
The suggested change wouls make sense when we have the emulation of video cards with this vram size in Bochs. Since Bochs doesn't emulate this video card yet, how do you get it working?

**Comment by Vort** [comment]
> Since Bochs doesn't emulate this video card yet, how do you get it working?

I made partial implementation for it.
Code is located in `geforce` branch of my fork right now: https://github.com/Vort/Bochs/tree/geforce.
With original video BIOS, [geforce3ti500.zip](https://github.com/user-attachments/files/18923815/geforce3ti500.zip), my code allows Ubuntu 10.04.4 to work pretty well.
However, it is possible just because Ubuntu 10.04.4 uses only single acceleration function of GeForce 3 Ti 500: hardware cursor.
With Ubuntu 12.04.5, things are more complicated, because it uses lots of acceleration features. Right now nothing is displayed after Ubuntu 12.04.5 loads, but I hope to change it soon.

**Comment by vruppert** [comment]
The required changes for the rombios32 code are more complicated than the suggested change from above. The presence of an AGP card and it's prefetchable and non-prefetchable memory must be checked before setting up the AGP memory registers. If no AGP card is installed the registers 0x20...0x23 and 0x24...0x27 must be set to 0x0000ffff. Otherwise these registers must be set to the upper 16 bits for base and limit of each memory type. The current value is correct for the Voodoo card and the suggested change is only correct for the experimental GeForce model. This is what I found out using a BIOS image for the i440BX chipset.

**Comment by Vort** [comment]
Meanwhile I added basic support for GeForce 6800 card emulation with 256 MB of VRAM.
Setting `pci_config_writew(d, 0x26, 0xf0f0);` allowed for it to kinda work, however:
1. It started to conflict with other devices like E1000, which wants to use the same `0xF0000000` region;
2. From [this link](http://knoppix.net/forum/threads/24197-iiyama-vision-master-pro-450-not-properly-detected) it looks like BAR2 of GeForce 6800 should be set like this: `Memory at de000000 (64-bit, non-prefetchable) [size=16M]`. However, when I try to remove `BX_GEFORCE_THIS pci_conf[0x18] = 0x08;` line from my code, card fails to initialize.

It well may be that these problems are related to what you explained.

> This is what I found out using a BIOS image for the i440BX chipset.

Can you suggest BIOSes for i440BX, which at least somehow work with Bochs?
It looks stupid, but I can't even get mouse working with Windows 7 x64 and `chipset=i440bx` (both PS2 and USB, both `BIOS-bochs-latest` and `i440fx.bin`).
Without knowing if bug is at BIOS side or at emulation side it is hard to make progress.

**Comment by vruppert** [comment]
I have now added some rombios32 code doing the things I described above. This made GitHub automatically close this issue, so I re-opened it to get your feedback. For testing with i440BX BIOS I have used GA-6BA_F1.bin here. The resource conflict with the Bochs BIOS is caused by the different memory regions used for AGP and PCI. AGP starts at 0xD0000000 and PCI starts at 0xE0000000. If the AGP card claims more than 256 MB of PCI memory, we'll have a conflict. I'll have a look what to do.

**Comment by Vort** [comment]
It works with GeForce FX 5900, but fails with GeForce3 Ti 500 and GeForce 6800 GT.
Probably because FX 5900 has no BAR2.

Tests were made with Windows 95 OSR 2 and [81.98 driver](https://download.nvidia.com/Windows/81.98/81.98_forceware_win9x_international.exe).
This driver will show lots of errors during OS load, but it is "fine", this is how NVIDIA supports Windows 95. Main functionality is not affected.

**Comment by Vort** [comment]
> For testing with i440BX BIOS I have used GA-6BA_F1.bin here.

I tried it, but it fails at two things:
1. At detecting HDD correctly. Theoretically, I can hackfix it by manually modifying HDD settings.
2. However, in practice BIOS fails also at saving settings to disk. Easy to test by changing boot sequence from "A,C,SCSI" to "C,A,SCSI", selecting "SAVE & EXIT SETUP" and restarting Bochs. Can you look what is wrong with it?

Because of bugs in my code, I can't proceed with testing without this feature working.

**Comment by vruppert** [comment]
For the GA-6BA_F1.bin BIOS I'm using a CMOS image (cmos.bin / 128 bytes) and added "flash_data:escd.bin" to the romimage option.

**Comment by vruppert** [comment]
I have now modified the AGP memory init code to get the right end address.

**Comment by Vort** [comment]
> For the GA-6BA_F1.bin BIOS I'm using a CMOS image (cmos.bin / 128 bytes)

It helped to some extent, however problems kept coming.
1. I wasn't able to boot already installed Windows 95, it just showed `WARNING: HLT instruction with IF=0!`.
2. Boot sequence is now at "C,A,SCSI" by default and can't be changed to "A,C,SCSI" to make fresh install of Windows from floppy.
3. When I copied CD driver to disk C manually and started Windows 95 setup from there, it produced panic message about PIC single mode not supported or something like that.

Windows allows to continue crashed installation with skipping of problematic step, and this is what I choose.
However, GeForce emulation fails to work with freshly installed Windows 95, either because of problems during installation or because I made mistakes in implementing something (probably, interrupt-related).

I will make tests with new `BIOS-bochs-latest` soon.

**Comment by Vort** [comment]
> I have now modified the AGP memory init code to get the right end address.

With this code, all 3 cards initialize successfully, as they are implemented right now.

However, I found [yet another evidence](https://forums.gentoo.org/viewtopic-p-2742024.html#2742024) that GeForce 6800 should have non-prefetchable BAR2:
```
  Bus  1, device   0, function  0:
    VGA compatible controller: nVidia Corporation NV40 [GeForce 6800] (rev 161).
      IRQ 16.
      Master Capable.  Latency=248.  Min Gnt=5.Max Lat=1.
      Non-prefetchable 32 bit memory at 0xed000000 [0xedffffff].
      Prefetchable 32 bit memory at 0xe0000000 [0xe7ffffff].
      Non-prefetchable 32 bit memory at 0xee000000 [0xeeffffff].
```

And when I try to configure GeForce 6800 like that, initialization fails.
I don't know if it worth trying to make it work like it should be.

**Comment by vruppert** [comment]
Comment for GA-6BA_F1.bin:
Issiue [1] is expected, since it's just like changing the mainboard.
Here it hangs in system management mode.
Changing the boot sequence works here. I can boot to DOS prompt works with both disk and floppy.
Please make sure that all of the disk and floppy settings in BIOS setup are correct (floppy type, onboard FDC, PCI IDE settings). I can boot with win95 install disk and start setup from cdrom, but then it hangs early after accepting license. On the BIOS boot screen I noticed that the wrong disk size is reported: test image should have 528 MB, but it reports 1000 GB.

Comment for Bochs BIOS:
I still have to change the PCI device init order to make sure there are no conflicts. The AGP device resources init must be done first - currently it's the last one. Using two passes for the PCI memory init could resolve the issue reported above.

**Comment by Vort** [comment]
> Please make sure that all of the disk and floppy settings in BIOS setup are correct (floppy type, onboard FDC, PCI IDE settings)

The thing is boot from floppy and boot from disk work fine when they are separated (only single image is attached).
It's just switching of boot sequence is not working.
Probably because of my mistake, but I can't find what I'm doing wrong.

> Changing the boot sequence works here. I can boot to DOS prompt works with both disk and floppy.

Please help to understand what is wrong with my configuration: [GA-6BA.ZIP](https://github.com/user-attachments/files/19270430/GA-6BA.ZIP).

> I can boot with win95 install disk and start setup from cdrom, but then it hangs early after accepting license.

Most likely, it is possible to start installation again, but choose to continue where it stopped (failed) instead of full reinstallation.

I made it like so, but then strange interrupt-related problem appeared:

When GA-6BA_F1 initializes, it assigns IRQ 11 to GeForce card:

![Image](https://github.com/user-attachments/assets/7a56af2e-81ef-4d7e-b727-92bbd7dc9016)

However, when I look with debugger, Bochs raises IRQ 5 instead when GeForce card calls `set_irq_level(1);`.

Here are logs related to IRQ, maybe they can help to understand what is going on:

```
00114988815i[GEFORC] new IRQ line = 255
00114997405i[UHCI  ] new IRQ line = 255
00114999604i[ACPI  ] new IRQ line = 255
00115002619i[NE2K0 ] new IRQ line = 255
...
00909875269i[GEFORC] new IRQ line = 11
00909875472i[P2ISA ] write: ELCR2 = 0x08
00909875497i[P2ISA ] PCI IRQ routing: PIRQA# set to 0x0b
00909875609i[UHCI  ] new IRQ line = 10
00909875812i[P2ISA ] write: ELCR2 = 0x0c
00909875849i[P2ISA ] PCI IRQ routing: PIRQD# set to 0x0a
00909875953i[ACPI  ] new IRQ line = 11
00909876303i[NE2K0 ] new IRQ line = 5
00909876504i[P2ISA ] write: ELCR1 = 0x20
00909876533i[P2ISA ] PCI IRQ routing: PIRQB# set to 0x05
```

**Comment by vruppert** [comment]
I made a lot of tests, but I didn't find out what's wrong with your setup. Some setting in the CMOS image seems to act like a write protection. So I decided to use my working image and modified all setup page step by step. After changing the last settings I could still change the boot sequence. Then I compared the binary files and I could see differences, but I don't know what they do. So please try with my CMOS image.

[cmos.zip](https://github.com/user-attachments/files/19272898/cmos.zip)

**Comment by Vort** [comment]
> I made a lot of tests, but I didn't find out what's wrong with your setup.

I figured it out.
Bochs forced me to create CMOS file by myself:
It created 1 byte file with `0x00`.
I added 127 more `0x00`s.

However, looks like it was wrong decision.
When I filled all 128 bytes with `0xFF`s, BIOS stopped glitching.

**Comment by vruppert** [comment]
I got such a 1 byte file yesterday after a panic caused by a typo in a VGBIOS image name. I could use a backup, so I had no trouble with image creation. Today I have fixed this 1 byte issue (saving image before CMOS init).

**Comment by Vort** [comment]
There is no 1 byte "hint" now, but user needs to know how to create file correctly anyway.
Looks like documentation issue. I expect something like this: "create 128 byte file filled with 0xFF bytes".

Also I see you made AGP-related changes. I will test them soon.

**Comment by Vort** [comment]
I see allocated addresses start at `0xC0000000` now. It should give more space for 256 MB card and use resources more efficiently, this is good.

> Using two passes for the PCI memory init could resolve the issue reported above.

However, it did not fixed 16 MB Non-prefetchable - 256 MB Prefetchable - 16 MB Non-prefetchable configuration mentioned before.

---

I was hoping to test this configuration with BIOS from real hardware.
But problem with interrupts prevents from doing this.
Should I try making separate issue about it?
I don't know yet how to reproduce it without code from my fork however.

**Comment by vruppert** [comment]
In the Bochs tree there is a file called make_cmos_image.c that writes an image for a specific configuration. I think it should be replaced by a tool that creates a file as described above.

I have written some code for a two pass PCI resource init, but something is wrong with it. The test with GeForce was okay, the resources were assigned as expected and the PCI AGP register set accordingly. I didn't try to boot an OS with this config. Then I tried the modified BIOS with my default config Win95 + Cirrus. The display was unuable and after reboot Windows reported a problem with the graphics card. I intend to start a second try soon.

I have now cloned the geforce branch of your Bochs repo since I want to build it on Linux. Then I'll try to install Win95 with a GeForce config.

**Comment by Vort** [comment]
There is a bug in my code, which prevents image from displaying after reboot, so in cases of black screens it is better to just restart Bochs. Other than that, with appropriate VBIOS (from archive above), I expect it to produce basic text and cursor output with drivers installed. Tests for AGP ranges, however, may be probably performed even without driver installed.
<details><summary>Expected output with Leadtek.6800GT.256.040702_AGP.bin, geforce: model=geforce6800
and 81.98 driver</summary>

![Image](https://github.com/user-attachments/assets/4063ed5d-c806-4bbe-99a4-c835b4b7ac58)

</details>

**Comment by vruppert** [comment]
I have now installed Win95 with the GeForce 6800. The first snapshot shows issues in text mode with this model. The other models are okay. To get the second snapshot I had to hack your code. You have modified the parameters of the redraw_area() method. That's why the vgacore never calls this overloaded method and that makes snapshot function fail. I have added a compatible version of redraw_area()  that calls your one. I suggest to rename it to avoid confusion.

If possible we should move this discussion to your GitHub page until the GeForce stuff is ready to apply it to the Bochs tree.

![Image](https://github.com/user-attachments/assets/bfe585ae-0414-4855-9bdd-7f3c1636ad1e)

![Image](https://github.com/user-attachments/assets/7df63fe2-2efb-4d38-a218-902b680bfb33)

**Comment by Vort** [comment]
> You have modified the parameters of the redraw_area() method.

That's how I tried to handle negative cursor coordinates.

> That's why the vgacore never calls this overloaded method and that makes snapshot function fail. I have added a compatible version of redraw_area() that calls your one. I suggest to rename it to avoid confusion.

Most likely fixed with https://github.com/Vort/Bochs/commit/ea44e4dff2f00d68e865aa95d73e019d83b4954f.

> If possible we should move this discussion to your GitHub page until the GeForce stuff is ready to apply it to the Bochs tree.

Some issues, like AGP ranges or interrupt handling, belong to main repository.
Some others, like `redraw_area`, belong to my fork.
Also some issues have unknown origin. Problem with text mode font is good example.
I made issue about it: https://github.com/Vort/Bochs/issues/1. However, until someone investigate it, it is hard to say why it happens.

By the way, it looks like GitHub automatically disables Issues section for forked repositories. I had to enable it manually.

> I have now installed Win95 with the GeForce 6800.

Ok, good.
I hope it works well enough to debug/test AGP-related problems.

**Comment by vruppert** [comment]
My second try with the Bochs BIOS did not work. I could fix the unwanted side effect that appeared with the Cirrus card and I finally got the resource setup we'd like to have. This made the GeForce stop working in Win95 due to a resource conflict. I haven't found out what was wrong then.

**Comment by Vort** [comment]
Such hack allows to avoid interrupt problem with GA-6BA_F1 _(but breaks boot with BIOS-bochs-latest)_:
```diff
diff --git a/bochs/iodev/pci2isa.cc b/bochs/iodev/pci2isa.cc
index 4335c09c3..ade0db2dc 100644
--- a/bochs/iodev/pci2isa.cc
+++ b/bochs/iodev/pci2isa.cc
@@ -224,7 +224,7 @@ void bx_piix3_c::pci_unregister_irq(unsigned pirq, Bit8u irq)
 
 void bx_piix3_c::pci_set_irq(Bit8u devfunc, unsigned line, bool level)
 {
-  Bit8u pirq = ((devfunc >> 3) + line - BX_P2I_THIS s.map_slot_to_dev) & 0x03;
+  Bit8u pirq = ((devfunc >> 3) + line - 1 - BX_P2I_THIS s.map_slot_to_dev) & 0x03;
 #if BX_SUPPORT_APIC
   // forward this function call to the ioapic too
   if (DEV_ioapic_present()) { 
```

With it applied I observed unexpected effect:
model=geforce3 and model=geforcefx5900 boot fine with GA-6BA_F1.
However, model=geforce6800 fails with resource conflict no matter if I configure BAR2 as prefetchable or not.
More investigation is needed to understand why it happens.

**Comment by Vort** [comment]
Looks like I know what went wrong with BAR0 Non-prefetchable - BAR1 Prefetchable - BAR2 Non-prefetchable configuration.
`pci_get_agp_memory` processes BARs sequentially: once it finds prefetchable BAR1, it decides that prefetchable range should start after BAR0.
This is wrong however. BAR0 and BAR2 ranges should be "glued together" and BAR1 should have addresses located after BAR2.

As for Cirrus problems, I can't reproduce them: with my Windows 95 installation, present `BIOS-bochs-latest` allocates `0xC0000000`-`0xC1FFFFFF` and `0xC2000000`-`0xC2000FFF` ranges for Cirrus Logic 5446 just fine. However, I made this test with `chipset=i440fx`.
As for `chipset=i440bx`, I remember problems with Cirrus card even before recent BIOS modifications, so it may well be an effect of some old bug.

**Comment by vruppert** [comment]
I have now attached the files from my tests of yesterday. It has no side effects with Cirrus and it sets up the GeForce resources and the PCI AGP registers to match the requirements from above. I have changed the BAR2 in your sources as it should be. The results in the log look okay to me, but my Win95 installation reports a resource conflict.

[rombios.zip](https://github.com/user-attachments/files/19349760/rombios.zip)

The IRQ problem with i440BX I need to investigate separately.

**Comment by Vort** [comment]
> it sets up the GeForce resources and the PCI AGP registers to match the requirements from above

> The results in the log look okay to me, but my Win95 installation reports a resource conflict.

It sets them up, but then corrupts what was done.
Setting up shows in logs, corruption is not.

**Comment by Vort** [comment]
> I have now applied an improved version of the two pass PCI resources init that works correctly.

I confirm correct work of GeForce 6800 with non-prefetchable BAR2 (https://github.com/Vort/Bochs/commit/b20cc28d622be8779ad702c8391c1f80823aee8b). Thank you.

![Image](https://github.com/user-attachments/assets/6ef393be-1729-47a4-90dc-c43b32bbb222)

This issue is effectively fixed, but may be used for discussion about interrupts if needed.

> Since the Voodoo AGP cards don't use the IRQ, I couldn't find out how to implement it correctly.

Why specifically Voodoo AGP is needed?
GeForce cards can be used as good indicator as well:
Driver _(win95, 81.98)_ will just hang without switching to high resolution mode during boot if interrupts are not delivered correctly.

> Tomorrow I'll have a look at the IRQ stuff in the AGP case.

I suspect other cards like ne2k may fail as well with GA-6BA_F1.
Here is a $PIR table for it:
![Image](https://github.com/user-attachments/assets/b1487619-709c-46a3-a926-6804482cd381)

Device 8 (0x40 >> 3) with INTA should correspond to PIRQA, I dont see it matching
`Bit8u pirq = ((devfunc >> 3) + line - BX_P2I_THIS s.map_slot_to_dev) & 0x03;` formula (considering `line` starts at `1` and `map_slot_to_dev` is equal to `8`).

**Comment by vruppert** [comment]
An installation of Win98SE using the GA-6BA_F1 BIOS and the GeForce card gives me some hints what needs to be done. I'll try to fix the PCI-AGP stuff on the weekend.

**Comment by Vort** [comment]
By the way, most likely, I ran into the same interrupt problem with GeForce card in Windows XP with Bochs BIOS. So it is not only GA-6BA_F1 which is affected.
_(both BIOS and GeForce emulation require hacks to work with XP, so I don't recommend trying to reproduce this effect right now, I'm saying about it just in case)_

**Comment by Vort** [comment]
Recent BIOS changes made memory BARs of AGP card aligned with ranges of AGP bridge.
However, it looks like the same approach needs to be applied to I/O ranges.
For example, in my tests with Voodoo 3, BIOS allocated `0xc000`-`0xc0ff` range for it. However, bridge range is configured to be different: `0xe000`-`0xffff`, which makes Windows to complain about conflict.

**Comment by Vort** [comment]
With 79ed0ca and Bochs BIOS, bx_acpi_ctrl_c::set_irq_level (devfunc 0x3b) tries to raise IRQ 11 despite being configured for IRQ 9, producing crash:
```
00001465598i[ACPI  ] new IRQ line = 11
00001465612i[ACPI  ] new IRQ line = 9
...
03251252281d[P2ISA ] INTA -> PIRQA -> IRQ 11 = 1
```
![Image](https://github.com/user-attachments/assets/12742c68-d900-476e-afc1-d1dedaad081e)

**Comment by vruppert** [comment]
The ACPI IRQ is assigned twice by the Bochs BIOS. The first one match the hardware config and second one is done after the comment that it should be "hardwired to 9". Since the real BIOS also uses IRQ 11 for ACPI, the comment and the related code are wrong. I'll have a look tomorrow.

**Comment by Vort** [comment]
During my test with `BIOS-bochs-latest` and 14baf7d, Windows 98 decided to move GeForce 6800 from IRQ 11 to IRQ 10, but Bochs still directed interrupts to IRQ 11:
```
00001449039i[GEFORC] new IRQ line = 11
...
00001463358i[UHCI  ] new IRQ line = 3
...
00001465608i[ACPI  ] new IRQ line = 11
...
00518806687i[UHCI  ] new IRQ line = 0
...
00533725780i[ACPI  ] new IRQ line = 9
...
00631080710i[GEFORC] new IRQ line = 10
...
INTA -> PIRQA -> IRQ 11 = 1
```

![Image](https://github.com/user-attachments/assets/0ef9e2ec-052e-4f5b-8724-4b31534e4c49)

Maybe because of ACPI tables you mentioned in commit comment, I don't know.
Also it may be important that I made my tests with USB controller disabled, I deactivated it long time ago when it was creating problems.

![Image](https://github.com/user-attachments/assets/3a704c08-95d6-4d0f-bd65-1199c4ebbcec)

---

I made test with GA-6BA_F1 as well (with GeForce FX 5900 instead), it allowed Windows 98 to detect and install bunch of new devices and then allocate IRQs like so:
```
00244987429i[GEFORC] new IRQ line = 255
...
00244995893i[UHCI  ] new IRQ line = 255
...
00244998092i[ACPI  ] new IRQ line = 255
...
01398549276i[GEFORC] new IRQ line = 11
...
01398549616i[UHCI  ] new IRQ line = 10
...
01398549960i[ACPI  ] new IRQ line = 11
...
01940473122i[UHCI  ] new IRQ line = 0
```

![Image](https://github.com/user-attachments/assets/7e6bbb10-d7db-4676-8077-9da0b10bd2a4)

However, shorty after load it crashed, looks like something is not right with timer interrupt once again.

**Comment by Vort** [comment]
> after the comment that it should be "hardwired to 9". Since the real BIOS also uses IRQ 11 for ACPI, the comment and the related code are wrong.

Source code for 86Box gave very valuable hint:
https://github.com/86Box/86Box/blob/fba4843cb0dfd99feea9b82e152da1ab4e91e32e/src/chipset/intel_piix.c#L1391

I checked documentation and turned out we missed important information:

![Image](https://github.com/user-attachments/assets/8a306182-f279-4776-ac79-7ff9a21ed285)

**Comment by vruppert** [comment]
I didn't know this document and now the question is what we should do now. I can revert this part of the BIOS changes and I can remove INT pin for ACPI. Replacing the PCI IRQ stuff by a direct connection to the PIC causes an IRQ conflict with the PCI IRQ router, since Bochs doesn't allow IRQ sharing at ISA level (it panics).

**Comment by Vort** [comment]
The problem is that my understanding of this topic is poor.
From [this](https://github.com/bochs-emu/Bochs/issues/452#issuecomment-2604958328) screenshot it looks like there are 4 categories of interrupts which can occupy IRQ9. And real hardware does not support sharing with ISA as well (_"ISA IRQ lost"_). However, from your description it looks like Bochs can't support sharing between SCI and PIRQ as well, which real hardware should be ok with.
I think it makes sense to:
1. Fix remaining interrupt problems ignoring SCI problem for now;
2. Fix [regression with Voodoo 3 I/O ranges](https://github.com/bochs-emu/Bochs/issues/485#issuecomment-2742026851);
3. Close this issue and continue discussion about SCI in #452. I will make link to this issue there soon.

**Comment by vruppert** [comment]
I'd like to review the Bochs IRQ handling and try to fix some IRQ related issues then. I agree, since the ACPI IRQ handling is not specific to AGP, this issue should be closed and discussion should continue with another one. The AGP i/o issue needs to be fixed in the same way as the memory issue.

**Comment by fysnet** [comment]
Volker,

I am not well versed in the IRQ handling as well, however, I have a few thoughts (opinions).
 * The current BIOS doesn't treat the ELCR registers correctly.
    The two ELCR registers simply indicate if the irq is edge driven or level driven.
    The current BIOS simply sets the corresponding bit if we declare the IRQ in `pci_irqs`
    In my opinion, the ELCR registers (0x4D0 and 0x4D1) should contain a value of `1101111011111000b` no matter what irqs we select. irqs 0,1,2,8, and 13 must be edge triggered (ISA), while the others can be (not _must be_, but _can be_) level triggered.
 * Second, registers 0x60 through 0x63 indicate which irq is associated with which pin number.
   Register 0x60 indicates pinA, 0x61 is pinB, etc.
   So with `static uint8_t pci_irqs[4] = { 11, 9, 5, 3 };`, pinA is irq 11, pinB is irq 9, etc.
   With this in mind, the (PCI) video card can be set to use pinA (irq 11), the USB can be set to use pinB (irq 9), leaving irq 5 and irq 3 for other use.
   
I am looking into a few other things too, and will comment if I see something. Just some thoughts I had.

**Comment by Vort** [comment]
I'm not familiar with ELCR at all.
However, your description of steering does not look right.
If I understand correctly, mapping from device interrupt pin to IRQ number is performed in two steps:
First, device interrupt pin is mapped to PIRQ (based on device number), then PIRQ is mapped to IRQ.
Both device pin and mapping to PIRQ is specified by hardware, BIOS can't (and shouldn't try to) change it.
BIOS can manipulate second part of mapping, but it is not much important which device will go where, they should work fine in all configurations; what important is that there should be no conflicts with non-PCI interrupts.
Also operating system can (and eventually will) change mapping made by BIOS, so initial configuration is more like suggestion.

**Comment by Vort** [comment]
After 248deda successfully fixed Voodoo 3 support, no more easily visible regressions left, so I think it's ok to close this issue. Thank you.
